[package]
name = "dypdl-heuristic-search"
version = "0.3.0"
edition = "2021"
description = "Heristic search solvers for Dynamic Programming Description Language (DyPDL)."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "3.0"
dypdl = { path = "../dypdl", version = "0.3" }
rustc-hash = "1.1"
